### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by dmi3kno** [mcanouil/quarto-letter#10]
I see that the template does not support sections or subsections. It is really sad, because adding structure to the document is always nice. Please, consider allowing section headers defined by Quarto # signs

**Comment by mcanouil** [comment]
To give some context, the extension was created to address a use case of mine which did not require "complexity".
It's deliberate that this extension only provides a simple output.

See <https://github.com/mcanouil/awesome-quarto#pdf-documents> for other "letter" formats which might suits your needs better or do as others, forked and customise (https://github.com/compies/quarto-letter).
