### ISSUE TITLE
Subject language

### ISSUE THREAD

**Issue by sebacea** [mcanouil/quarto-letter#11]
Hi, thanks for this template. I am writing a letter in Spanish and adding option `lang: es` to the yaml was sufficient to have the date in Spanish. Nevertheless, prefix "Subject" to the subject of the letter remain in English. I was not able to understand how to improve `partials/before-body.tex` to make "Subject" word depending on the language. Or, alternatively, to change it directly.

I will really appreciate some guidance.

**Comment by mcanouil** [comment]
This is tricky, because this would require to have a translation file which I don't have.
One thing I can easily do is to add a yaml parameter to overwrite the prefix.

**Comment by sebacea** [comment]
I know. The most efficient solution is what you propose I guess.

Thanks!

Le mer. 12 juil. 2023 à 11:32, Mickaël Canouil ***@***.***> a
écrit :

**Comment by mcanouil** [comment]
Actually, I already implemented this:

```yaml
subject-title: "Asunto"
```
