### ISSUE TITLE
Adding Letterhead to template

### ISSUE THREAD

**Issue by drfurtado** [mcanouil/quarto-letter#12]
I am wondering if it's possible to add a letterhead (a .jpg file) to the top of a letter template.
Great template, BTW.

**Comment by mcanouil** [comment]
Well yes, it's possible.
You only need to add a new yaml option and set where in the latex template it should go.

Note that this extension is really a simple letter.
Checkout Quarto website for the extension listing and/or the Awesome Quarto list for other letter formats.
