### ISSUE TITLE
Would it possible to add top logo and after letter signature?

### ISSUE THREAD

**Issue by drganghe** [mcanouil/quarto-letter#3]
I was searching for a letter template for the quarto, and thank you for making this available. 

It would be very helpful if a logo and signature option (and control of position) is available. Just an idea.

Again, thanks for the template.

**Comment by mcanouil** [comment]
What exactly do you mean by signature?

**Comment by drganghe** [comment]
Thanks for the response. For example, I'm writing a letter and would like to add a University logo at the top and a scanned signature (picture) after closing.

**Comment by mcanouil** [comment]
I see.
I usually signed my PDF using PDF viewer.

This can be done by adding two yaml options and the corresponding LaTeX code although I don't know when exactly I'll do it.

**Comment by mcanouil** [comment]
In the end, I think I am going to keep this as simple as it is.

Although, you might be interested in the following letter template extensions to, for example, define one for your custom needs:
- https://github.com/numbats/monash-quarto-letter
- https://github.com/nareal/naletter
- https://github.com/juliantao/qletter
