### ISSUE TITLE
Scrlttr2

### ISSUE THREAD

**Issue by compies** [mcanouil/quarto-letter#9]
I spent this sunday playing around with your extension and very much liked the idea to get letters out of as little as possible markdown files. I adapted this to my own used sclttr2 template latex template. I extended it with a lot of the Komascript builtin Variables to make it look more like a usual current letter .

Before I fork and release just the same again I would rather appreciate if you would be interested in these code snippets. 
I still got some minor issues like shortened phone numbers due to yaml features but itts working at least for me pretty well. 

Looking forward for your response 
compies

**Comment by mcanouil** [comment]
Thanks for the interest.
FYI, this extension was mostly created because I needed it for a really simple letter.

There is no issue as publishing a new Quarto extension, see <https://github.com/mcanouil/awesome-quarto#pdf-documents>. There are already several "letter" Quarto extension.

**Comment by compies** [comment]
Forked it - hope you like it!
